[package]
name = "Linear_regression"
version = "0.1.0"
edition = "2024"

[dependencies]
candle-core = { version = "0.8.4", features = ["metal"] }
candle-nn = { version = "0.8.4", features = ["metal"] }
